name: Notify Telegram on New Issue

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send formatted Telegram message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPO_NAME: ${{ github.repository }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_USER: ${{ github.event.issue.user.login }}
          ISSUE_TAG: ${{ github.event.issue.labels[0].name }}
        run: |
          # Escape characters for Telegram MarkdownV2 (you can also use 'HTML' instead)
          ESCAPED_REPO_NAME=$(echo "$REPO_NAME" | sed 's/\./\\./g')
          ESCAPED_ISSUE_TITLE=$(echo "$ISSUE_TITLE" | sed 's/\[/\\[/g; s/\]/\\]/g; s/\*/\\*/g')
          
          MESSAGE="*$ESCAPED_REPO_NAME* \[$ISSUE_TAG\] - @$ISSUE_USER%0A[$ESCAPED_ISSUE_TITLE]($ISSUE_URL)"
          
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"